tjmSiteHome:
 pattern: "{slash}"
 defaults: {_controller: TJMSiteBundle:Default:index, slash: ""}
 requirements:
  slash: /?

tjmTMComTest:
 pattern: /test{parameters}
 defaults: {_controller: TJMSiteBundle:Default:test}
 requirements:
  parameters: .*

tjmSiteSimplePage:
 pattern: /{name}
 defaults: {_controller: TJMSiteBundle:Default:simplePage}
