imports:
 - {resource: config.yml}
 - {resource: @TJMBaseBundle/Resources/config/config_prod.yml}

#==Doctrine
#doctrine:
# orm:
#  metadata_cache_driver: apc
#  result_cache_driver: apc
#  query_cache_driver: apc
