imports:
 - {resource: parameters.yml}
 - {resource: security.yml}
 - {resource: @TJMBaseBundle/Resources/config/config.yml}
 - {resource: @TJMStandardEditionBundle/Resources/config/config.yml}

#==Assetic
assetic:
 bundles:
  - TJMSiteBundle
 write_to: %kernel.root_dir%/../web/_assets
