imports:
 - {resource: parameters.yml}
 - {resource: security.yml}
 - {resource: '@TJMBaseBundle/Resources/config/config.yml'}
 - {resource: '@TJMStandardEditionBundle/Resources/config/config.yml'}

parameters:
 twig.extension.assets.class: TJM\Bundle\BaseBundle\Extension\AssetsExtension
