_app_pre:
 resource: "@AppBundle/Resources/config/routing.pre.yml"

_TJMBase:
 resource: "@TJMBaseBundle/Resources/config/routingBase.yml"

_app_post:
 resource: "@AppBundle/Resources/config/routing.post.yml"
