security:
 firewalls:
  dev:
   pattern: ^/(_(profiler|wdt)|css|images|js)/
   security: false
  main:
   security: true
   anonymous: true
 providers:
  in_memory:
   users:
    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
