#!/usr/bin/env php
<?php
use TJM\Shared\Component\Config;

// if you don't want to setup permissions the proper way, just uncomment the following PHP line
// read http://symfony.com/doc/current/book/installation.html#configuration-and-setup for more information
//umask(0000);

require_once(__DIR__ . '/init.php');
require_once(Config::$paths['shared'] . "/app/console");
