appHome:
 path: "{slash}"
 defaults: {_controller: AppBundle:Default:index, slash: ""}
 requirements:
  slash: /?

appTest:
 path: /test{parameters}
 defaults: {_controller: AppBundle:Default:test}
 requirements:
  parameters: .*

appSimplePage:
 path: /{name}
 defaults: {_controller: AppBundle:Default:simplePage}
