##==meta
appRobots:
 path: /robots.{_format}
 defaults: {_controller: AppBundle:Meta:robots, _format: 'html'}

##==default
appHome:
 path: "{slash}"
 defaults: {_controller: AppBundle:Default:index, slash: ""}
 requirements:
  slash: /?

appTest:
 path: /test{parameters}
 defaults: {_controller: AppBundle:Default:test}
 requirements:
  parameters: .*

appSimplePage:
 path: /{name}
 defaults: {_controller: AppBundle:Default:simplePage}

##==base
_TJMBase:
 resource: "@TJMBaseBundle/Resources/config/routingBase.yml"

##==post
remove_trailing_slash:
 path: /{url}
 defaults: {_controller: AppBundle:Default:removeTrailingSlash}
 methods: [GET]
 requirements:
  url: .*/$
